use images from /cvmfs/cms-ib; properly run user command

diff --git a/_cmssw-osenv b/_cmssw-osenv
--- a/_cmssw-osenv
+++ b/_cmssw-osenv
@@ -3,11 +3,11 @@ SINGULARITY_OPTS=
 while [ "$#" != 0 ]; do
   case "$1" in
     -h|--help)
-      echo "Usage: $0 [-h|--help] [singularity-options] [--command-to-run <command to run>]"
-      echo "Environment variable UNPACK_IMAGE can be set to point to either valid docker/singularity image or unpacked image path"
+      echo "Usage: $0 [-h|--help] [singularity-options] [--command-to-run|-- <command to run>]"
+      echo "Environment variable UNPACKED_IMAGE can be set to point to either valid docker/singularity image or unpacked image path"
       exit 0
       ;;
-    --command-to-run)
+    --command-to-run|--)
       shift
       break
       ;;
@@ -19,27 +19,30 @@ while [ "$#" != 0 ]; do
 done
 
 if [ "X${UNPACKED_IMAGE}" = "X" ] ;then
-  UNPACKED_REPO="/cvmfs/unpacked.cern.ch"
-  ls ${UNPACKED_REPO} >/dev/null 2>&1 || true
-  UNPACKED_PATH="${UNPACKED_REPO}/registry.hub.docker.com"
   SCRIPT_NAME=$(basename $0)
   case $SCRIPT_NAME in
     cmssw-cc6) SCRIPT_NAME=cmssw-slc6;;
   esac
   DOCKER_NAME=
-
   case $SCRIPT_NAME in
     cmssw-cc*|cmssw-slc*)
       DOCKER_NAME="$(echo $SCRIPT_NAME | sed 's|-|/|'):latest"
       ;;
-    *) 
+    *)
       echo "ERROR: Unknown unpacked image: $(echo $SCRIPT_NAME | sed 's|-|/|'):latest or cmssw/$(echo $SCRIPT_NAME | sed 's|-|:|')"
       exit 1
       ;;
   esac
-  UNPACKED_IMAGE="${UNPACKED_PATH}/${DOCKER_NAME}"
-  if [ ! -e ${UNPACKED_IMAGE} ] ; then
-    echo "ERROR: Unable to find ${UNPACKED_IMAGE}"
+  UNPACK_DIRS="/cvmfs/cms-ib.cern.ch/docker /cvmfs/unpacked.cern.ch/registry.hub.docker.com"
+  for dir in ${UNPACK_DIRS} ; do
+    ls ${dir} >/dev/null 2>&1 || true
+    if [ -e "${dir}/${DOCKER_NAME}" ] ; then
+      UNPACKED_IMAGE="${dir}/${DOCKER_NAME}"
+      break
+    fi
+  done
+  if [ "${UNPACKED_IMAGE}" = "" ] ; then
+    echo "ERROR: Unable to find ${DOCKER_NAME} under ${UNPACK_DIRS}"
     exit 1
   fi
 fi
@@ -67,11 +70,12 @@ if [ -e $UNPACKED_IMAGE ] ; then
   done
   export SINGULARITY_BINDPATH=$(echo ${VALID_MOUNT_POINTS} | sed 's|^,||')
 fi
-PREFIX_CMD='true'
 SINGULARITY_OPTS="${SINGULARITY_OPTS} --home ${HOME}:/home/$(whoami)"
-if [ -e /cvmfs/cms.cern.ch/cmsset_default.sh ] ; then PREFIX_CMD='source /cvmfs/cms.cern.ch/cmsset_default.sh'; fi
+CMD_TO_RUN="export HOME=/home/$(whoami)"
+if [ -e /cvmfs/cms.cern.ch/cmsset_default.sh ] ; then CMD_TO_RUN="${CMD_TO_RUN}; source /cvmfs/cms.cern.ch/cmsset_default.sh"; fi
 if [[ "$@" = "" ]] ; then
-  singularity -s exec ${SINGULARITY_OPTS} $UNPACKED_IMAGE sh -c "/bin/bash; $PREFIX_CMD"
+  CMD_TO_RUN="${CMD_TO_RUN}; /bin/bash"
 else
-  singularity -s shell ${SINGULARITY_OPTS} $UNPACKED_IMAGE -c "$PREFIX_CMD; $@"
+  CMD_TO_RUN="${CMD_TO_RUN}; $@"
 fi
+singularity -s exec ${SINGULARITY_OPTS} $UNPACKED_IMAGE sh -c "$CMD_TO_RUN"
