add nohup option to use apptainer instance to run persistently in background

diff --git a/cmssw-env b/cmssw-env
--- a/cmssw-env
+++ b/cmssw-env
@@ -7,6 +7,8 @@ THISDIR=$(dirname $0)
 IGNORE_MOUNTS=""
 SHOW_COMMAND="true"
 INTERACTIVE=""
+NOHUP=""
+QUIET=""
 CONTAINER_CMD="singularity"
 BINDPATH_ENV="SINGULARITY_BINDPATH"
 MOUNT_POINTS="${SINGULARITY_BINDPATH}"
@@ -20,17 +22,32 @@ while [ "$#" != 0 ]; do
     -h|--help)
       HELP_ARG=""
       if [ "${CMS_IMAGE}" = "${BASE_SCRIPT}" ] ; then HELP_ARG="[--cmsos <image>] "; fi
-      echo "Usage: $0 [-h|--help] ${HELP_ARG}[extra-options] [--show-command] [--ignore-mount <dir1[,dir2[,...]]>] [--interactive] [--command-to-run|-- <command(s)>]"
+      echo "Usage: $0 [-h|--help] ${HELP_ARG}[extra-options] [--show-command] [--ignore-mount <dir1[,dir2[,...]]>] [--interactive] [--nohup] [-q/--quiet] [--command-to-run|-- <command(s)>]"
       echo "Environment variable UNPACKED_IMAGE can be set to point to either valid docker/singularity image or unpacked image path"
       echo "If <command> includes multiple commands separated by ; or &&, or other high-precedence shell operators like >, it must be quoted"
       echo "--ignore-mount /dir        To not explicitly mount /dir"
       echo "--interactive              To start the shell in interactive mode"
+      echo "--nohup                    Create an instance to run in background"
       echo "--command-to-run <command> To run <command> and exit."
       exit 0
       ;;
     --show-command) SHOW_COMMAND="set -x"; shift ;;
     --ignore-mount) IGNORE_MOUNTS=$(echo $2 | tr ',' ' '); shift; shift ;;
-    --interactive) INTERACTIVE="-l -i"; shift ;;
+    --interactive)
+      if [ -n "$NOHUP" ]; then
+        echo "ERROR: incompatible options --interactive and --nohup"
+        exit 1
+      fi
+      INTERACTIVE="-l -i"; shift ;;
+    --nohup)
+      if [ -n "$INTERACTIVE" ]; then
+        echo "ERROR: incompatible options --interactive and --nohup"
+        exit 1
+      fi
+      # get a random container name
+      NOHUP="$(mktemp -u ${CMS_IMAGE}-XXXXXX)"; shift ;;
+    -q|--quiet)
+      QUIET="true"; shift ;;
     --cmsos)
       if [ "${CMS_IMAGE}" != "${BASE_SCRIPT}" ] ; then
         echo "ERROR: Unknown option '--cmsos' found. This option is only valid for ${BASE_SCRIPT} command."
@@ -51,6 +68,12 @@ while [ "$#" != 0 ]; do
       ;;
   esac
 done
+
+if [ -n "$NOHUP" ] && [ -z "QUIET" ]; then
+  echo "You are starting an independent instance!"
+  echo "This instance will keep running until you stop it manually with the following command:"
+  echo "$CONTAINER_CMD instance stop $NOHUP"
+fi
 
 if [ "${CMS_IMAGE}" = "cmssw-el6" ] ; then
   #Always use SCRAM V2 for el6
@@ -159,4 +182,9 @@ fi
 #Containers might not have all locales installed, so force set  LC_ALL=C
 export LC_ALL="C"
 
-${SHOW_COMMAND} ; ${CONTAINER_CMD} -s exec ${EXTRA_OPTS} $UNPACKED_IMAGE sh -c "${RESET_SCRAM_ARCH} /bin/bash ${INTERACTIVE}""${FINAL_CMD_TO_RUN}"
+INSTANCE=$UNPACKED_IMAGE
+if [ -n "$NOHUP" ]; then
+  INSTANCE=instance://$NOHUP
+  ${SHOW_COMMAND} ; ${CONTAINER_CMD} -s instance start $UNPACKED_IMAGE $NOHUP
+fi
+${SHOW_COMMAND} ; ${CONTAINER_CMD} -s exec ${EXTRA_OPTS} $INSTANCE sh -c "${RESET_SCRAM_ARCH} /bin/bash ${INTERACTIVE}""${FINAL_CMD_TO_RUN}"
